package com.edgefort.simulator.config;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeIn;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.License;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import org.springframework.context.annotation.Configuration;

@Configuration
@OpenAPIDefinition(
        info = @Info(
                title = "Simulator API",
                version = "v1",
                description = "Lightweight, storage-free payment provider simulation API",
                license = @License(name = "Provisional provider contracts")
        )
)
@SecurityScheme(
        name = "AdminToken",
        description = "Token required by simulator administration endpoints",
        type = SecuritySchemeType.APIKEY,
        in = SecuritySchemeIn.HEADER,
        paramName = "X-Admin-Token"
)
@SecurityScheme(
        name = "InterswitchBearerToken",
        description = "Bearer access token generated by the simulated Interswitch OAuth endpoint",
        type = SecuritySchemeType.HTTP,
        scheme = "bearer"
)
public class OpenApiConfiguration {
}